import { ReactNode, useEffect, useMemo, useState } from 'react'
import { AgentEvent, Chapter, Character, Fact, json, ModelConfig, Novel, request, streamAgentRun, Timeline } from './api'

type Workspace={novel:Novel;chapters:Chapter[];characters:Character[];facts:Fact[];timeline:Timeline[]}
type Issue={type:string;severity:string;description:string;suggestion:string}
type Proposal={master_outline?:string;chapters?:any[];change_summary?:string;reasoning_summary?:string;affected_chapters?:number[];warnings?:string[];outline?:{content:string;chapters:any[]}}
const newNovel={title:'',genre:'',theme:'',target_words:80000,default_style:''}
const api=(path:string,method='GET',body?:unknown)=>request<any>(path,json(method,body))

function Modal({children,close}:{children:ReactNode;close:()=>void}){return <div className="veil"><section className="modal"><button className="icon close" onClick={close}>×</button>{children}</section></div>}

export default function App(){
 const [novels,setNovels]=useState<Novel[]>([]),[workspace,setWorkspace]=useState<Workspace|null>(null),[chapterId,setChapterId]=useState<number|null>(null),[notice,setNotice]=useState(''),[create,setCreate]=useState(false),[modelSettings,setModelSettings]=useState(false)
 const tell=(text:string)=>{setNotice(text);window.setTimeout(()=>setNotice(''),4500)}
 const loadShelf=()=>request<Novel[]>('/novels').then(setNovels).catch((e:Error)=>tell(e.message))
 const open=async(id:number,select?:number)=>{try{const w=await request<Workspace>(`/novels/${id}/workspace`);setWorkspace(w);setChapterId(select??w.chapters[0]?.id??null)}catch(e:any){tell(e.message)}}
 useEffect(()=>{loadShelf()},[])
 const createNovel=async(data:any)=>{try{const n=await api('/novels','POST',data);setCreate(false);await loadShelf();await open(n.id);tell('小说已创建')}catch(e:any){tell(e.message)}}
 const removeNovel=async(n:Novel)=>{if(!window.confirm(`确定永久删除《${n.title}》吗？\n\n这会删除该小说的全部大纲、章节、正文、人物、时间线、摘要、设定事实和 AI 记录，且无法恢复。`))return;try{await api(`/novels/${n.id}`,'DELETE');if(workspace?.novel.id===n.id)setWorkspace(null);await loadShelf();tell('小说已删除')}catch(e:any){tell(e.message)}}
 const chapter=useMemo(()=>workspace?.chapters.find(x=>x.id===chapterId)||workspace?.chapters[0],[workspace,chapterId])
 return <>{workspace?<Workbench workspace={workspace} chapter={chapter} select={setChapterId} refresh={(id?:number)=>open(workspace.novel.id,id??chapter?.id)} back={()=>{setWorkspace(null);loadShelf()}} removeNovel={()=>removeNovel(workspace.novel)} tell={tell} openModels={()=>setModelSettings(true)}/>:<Shelf novels={novels} open={open} create={()=>setCreate(true)} remove={removeNovel} openModels={()=>setModelSettings(true)}/>} {create&&<NovelForm close={()=>setCreate(false)} submit={createNovel}/>} {modelSettings&&<ModelSettings close={()=>setModelSettings(false)} tell={tell}/>} {notice&&<div className="toast">{notice}</div>}</>
}

function Shelf({novels,open,create,remove,openModels}:{novels:Novel[];open:(id:number)=>void;create:()=>void;remove:(n:Novel)=>void;openModels:()=>void}){return <main className="shelf"><header><div><p className="eyebrow">NOVELWRITER</p><h1>你的故事，从这里长出来。</h1><p className="sub">每一部小说都有独立的创作记忆与设定。</p></div><div><button className="ghost" onClick={openModels}>模型设置</button><button onClick={create}>＋ 新建小说</button></div></header><div className="book-grid">{novels.map((n,i)=><article className={`book book-${i%4}`} key={n.id}><button className="book-open" onClick={()=>open(n.id)}><span>{n.genre||'未分类'}</span><h2>{n.title}</h2><p>{n.theme||'尚未写下故事主旨'}</p><footer>{n.target_words?.toLocaleString()||'—'} 字目标</footer></button><button className="book-delete" onClick={()=>remove(n)}>删除</button></article>)}{!novels.length&&<div className="empty"><span>✦</span><h2>书架还是空的</h2><p>创建第一本小说，开始建立属于它的世界。</p><button onClick={create}>创建小说</button></div>}</div></main>}

function NovelForm({close,submit}:{close:()=>void;submit:(data:any)=>void}){const[f,setF]=useState(newNovel);const on=(e:any)=>setF({...f,[e.target.name]:e.target.name==='target_words'?Number(e.target.value):e.target.value});return <Modal close={close}><p className="eyebrow">NEW NOVEL</p><h2>创建一本小说</h2><form className="form" onSubmit={e=>{e.preventDefault();submit(f)}}><label>书名<input required name="title" value={f.title} onChange={on}/></label><div className="two"><label>题材<input name="genre" value={f.genre} onChange={on}/></label><label>目标字数<input name="target_words" type="number" value={f.target_words} onChange={on}/></label></div><label>故事主旨<textarea name="theme" value={f.theme} onChange={on}/></label><label>默认文风<textarea name="default_style" value={f.default_style} onChange={on}/></label><div className="actions"><button type="button" className="ghost" onClick={close}>取消</button><button>创建并进入</button></div></form></Modal>}

function ModelSettings({close,tell}:{close:()=>void;tell:(x:string)=>void}){
 const blank={display_name:'',api_base_url:'https://api.deepseek.com',api_key:'',model_id:'deepseek-chat',default_temperature:0.7,max_output_tokens:''}
 const [items,setItems]=useState<ModelConfig[]>([]),[form,setForm]=useState<any>(blank),[editing,setEditing]=useState<string|null>(null),[loading,setLoading]=useState(false)
 const load=()=>request<ModelConfig[]>('/model-configs').then(setItems).catch((e:Error)=>tell(e.message));useEffect(()=>{load()},[])
 const change=(e:any)=>setForm({...form,[e.target.name]:e.target.value})
 const edit=(m:ModelConfig)=>{setEditing(m.id);setForm({display_name:m.display_name,api_base_url:m.api_base_url,api_key:'',model_id:m.model_id,default_temperature:m.default_temperature,max_output_tokens:m.max_output_tokens||''})}
 const save=async(e:any)=>{e.preventDefault();try{setLoading(true);const body={...form,provider_type:'openai_compatible',supported_tasks:[],default_temperature:Number(form.default_temperature),max_output_tokens:form.max_output_tokens?Number(form.max_output_tokens):null};if(editing&&!body.api_key)delete body.api_key;await api(editing?`/model-configs/${editing}`:'/model-configs',editing?'PATCH':'POST',body);await load();window.dispatchEvent(new Event('model-configs-updated'));tell('模型已安全保存');close()}catch(e:any){tell(e.message)}finally{setLoading(false)}}
 const update=async(m:ModelConfig,body:any)=>{try{await api(`/model-configs/${m.id}`,'PATCH',body);await load()}catch(e:any){tell(e.message)}}
 const remove=async(m:ModelConfig)=>{if(!window.confirm(`删除模型「${m.display_name}」？此操作不可恢复。`))return;try{await api(`/model-configs/${m.id}`,'DELETE');await load()}catch(e:any){tell(e.message)}}
 return <Modal close={close}><div className="settings-head"><div><p className="eyebrow">创作模型</p><h2>模型设置</h2><p className="muted">一个模型默认可用于所有创作功能；Key 已加密，始终只显示掩码。</p></div></div><div className="model-list">{items.map(m=><div className="model-card" key={m.id}><div><b>{m.display_name}</b>{m.is_default&&<i>默认模型</i>}<span>{m.model_id} · {m.enabled?'可用':'已停用'}</span><small>{m.api_key_masked}　{m.last_test_message||'尚未测试连接'}</small></div><div className="model-actions"><button className="tiny" onClick={()=>edit(m)}>编辑</button><button className="tiny" onClick={()=>update(m,{enabled:!m.enabled})}>{m.enabled?'停用':'启用'}</button><button className="tiny" onClick={()=>update(m,{is_default:true})}>设为默认</button><button className="tiny" onClick={async()=>{await api(`/model-configs/${m.id}/test`,'POST');await load()}}>测试连接</button><button className="tiny danger-link" onClick={()=>remove(m)}>删除</button></div></div>)}</div><form className="form model-form" onSubmit={save}><h3>{editing?'编辑模型':'添加模型'}</h3><label>配置名称<input name="display_name" required value={form.display_name} onChange={change} placeholder="例如：我的 DeepSeek"/></label><label>API Base URL <button type="button" className="link-button" onClick={()=>setForm({...form,api_base_url:'https://api.deepseek.com'})}>使用 DeepSeek 默认地址</button><input name="api_base_url" required value={form.api_base_url} onChange={change}/></label><label>API Key {editing&&<small>（留空则不更新）</small>}<input type="password" name="api_key" required={!editing} value={form.api_key} onChange={change} autoComplete="new-password"/></label><div className="two"><label>模型名称<input name="model_id" required value={form.model_id} onChange={change}/></label><label>默认 Temperature<input type="number" name="default_temperature" min="0" max="2" step="0.1" value={form.default_temperature} onChange={change}/></label></div><label>最大输出 Token（可选）<input type="number" name="max_output_tokens" value={form.max_output_tokens} onChange={change}/></label><p className="muted">0–0.4 更稳定；0.5–0.9 适合日常创作；1.0 以上更有创意。</p><div className="actions"><button type="button" className="ghost" onClick={()=>{setEditing(null);setForm(blank)}}>取消编辑</button><button disabled={loading}>{loading?'保存中…':'保存模型'}</button></div></form></Modal>
}

function Workbench({workspace,chapter,select,refresh,back,removeNovel,tell,openModels}:{workspace:Workspace;chapter?:Chapter;select:(n:number)=>void;refresh:(n?:number)=>void;back:()=>void;removeNovel:()=>void;tell:(x:string)=>void;openModels:()=>void}){
 const [tab,setTab]=useState<'write'|'outline'>('write'),[busy,setBusy]=useState(false),[issues,setIssues]=useState<Issue[]>([]),[proposal,setProposal]=useState<Proposal|null>(null),[runEvents,setRunEvents]=useState<AgentEvent[]>([]),[runId,setRunId]=useState(''),[runs,setRuns]=useState<any[]>([]),[models,setModels]=useState<ModelConfig[]>([]),[modelId,setModelId]=useState(''),[temperature,setTemperature]=useState<number>(0.7)
 const loadRuns=()=>request<any[]>(`/novels/${workspace.novel.id}/agent-runs`,).then(setRuns).catch(()=>{})
 useEffect(()=>{loadRuns()},[workspace.novel.id,chapter?.id])
 const loadModels=()=>request<ModelConfig[]>('/model-configs').then(items=>{const enabled=items.filter(x=>x.enabled);setModels(enabled);const preferred=enabled.find(x=>x.id===workspace.novel.default_writing_model_config_id)||enabled.find(x=>x.is_default)||enabled[0];if(preferred){setModelId(current=>enabled.some(x=>x.id===current)?current:preferred.id);setTemperature(current=>current===0.7?preferred.default_temperature:current)}}).catch(()=>{})
 useEffect(()=>{loadModels();const sync=()=>loadModels();window.addEventListener('model-configs-updated',sync);return()=>window.removeEventListener('model-configs-updated',sync)},[workspace.novel.id])
 const execute=async(task_type:string,input:object,chapter_id?:number,onEvent?:(event:AgentEvent)=>void)=>{let result:any;setRunEvents([]);setRunId('');await streamAgentRun(`/novels/${workspace.novel.id}/agent-runs/stream`,{task_type,chapter_id,input,model_config_id:modelId||undefined,temperature},event=>{setRunId(event.run_id);setRunEvents(old=>[...old.slice(-39),event]);if(event.event_type==='result')result=event.data;onEvent?.(event)});await loadRuns();return result}
 const setNovelModel=async()=>{if(!modelId)return tell('请先在模型设置中创建并启用模型');try{await api(`/novels/${workspace.novel.id}`,'PATCH',{default_writing_model_config_id:modelId,default_outline_model_config_id:modelId,default_review_model_config_id:modelId});await refresh();tell('已设为本小说默认模型')}catch(e:any){tell(e.message)}}
 const resume=async(id:string)=>{let result:any;setRunEvents([]);setRunId(id);await streamAgentRun(`/agent-runs/${id}/resume/stream`,{},event=>{setRunEvents(old=>[...old.slice(-39),event]);if(event.event_type==='result')result=event.data});await loadRuns();return result}
 const cancel=async(id:string)=>{await api(`/agent-runs/${id}/cancel`,'POST');await loadRuns();tell('已停止运行，草稿与上下文快照已保留')}
 const add=async()=>{const sequence=Math.max(0,...workspace.chapters.map(x=>x.sequence))+1;try{const c=await api(`/novels/${workspace.novel.id}/chapters`,'POST',{sequence,title:`第${sequence}章`,status:'draft'});await refresh(c.id)}catch(e:any){tell(e.message)}}
 const deleteChapter=async(c:Chapter)=>{const warning=c.status==='confirmed'?'\n\n此章节已确认，删除可能使后续章节的时间线、人物状态和大纲引用失效。':'';if(!window.confirm(`删除第 ${c.sequence} 章《${c.title}》？\n\n将删除正文、摘要、AI 任务以及直接关联的提取数据。${warning}`))return;try{await api(`/novels/${workspace.novel.id}/chapters/${c.id}`,'DELETE');await refresh();tell('章节已删除并重排后续序号；建议重新校验后续章节。')}catch(e:any){tell(e.message)}}
 const improveOutline=async(requestText:string)=>{try{setBusy(true);const result=await execute('improve_outline',{improvement_request:requestText});setProposal(result);setTab('outline')}catch(e:any){tell(e.message)}finally{setBusy(false)}}
 const createOutline=async()=>{try{setBusy(true);const result=await execute('generate_outline',{theme:workspace.novel.theme,genre:workspace.novel.genre,target_words:workspace.novel.target_words||80000,chapter_count:12,style:workspace.novel.default_style});setProposal({master_outline:result.master_outline,chapters:result.chapters});setTab('outline')}catch(e:any){tell(e.message)}finally{setBusy(false)}}
 const applyProposal=async(selected?:number[])=>{if(!proposal)return;const outline=proposal.outline?.content??proposal.master_outline;const rows=proposal.outline?.chapters??proposal.chapters??[];try{setBusy(true);await api(`/novels/${workspace.novel.id}/ai/apply-outline-improvement`,'POST',{master_outline:outline,chapters:rows,apply_chapter_numbers:selected});setProposal(null);await refresh();tell('已应用选择的草稿章节；已确认章节保持不变。')}catch(e:any){tell(e.message)}finally{setBusy(false)}}
 return <main className="workbench"><nav className="topbar"><button className="wordmark" onClick={back}>‹ 返回书架</button><div className="novel-identity"><strong>{workspace.novel.title}</strong><span>{workspace.novel.genre||'小说工作台'}</span></div><div className="top-actions"><div className="model-control"><select className="model-select" value={modelId} onChange={e=>{const item=models.find(x=>x.id===e.target.value);setModelId(e.target.value);if(item)setTemperature(item.default_temperature)}}><option value="">{models.length?'选择模型':'配置模型'}</option>{models.map(m=><option key={m.id} value={m.id}>{m.display_name}</option>)}</select><label>温度<input className="temp-input" type="number" min="0" max="2" step="0.1" value={temperature} onChange={e=>setTemperature(Number(e.target.value))}/></label></div><button className="icon-button" title="模型设置" onClick={openModels}>⚙</button><details className="more-menu"><summary title="更多操作" aria-label="更多操作">更多</summary><div className="more-popover"><button onClick={setNovelModel}>设为本书默认模型</button></div></details><div className="view-switch"><button className={tab==='write'?'selected':''} onClick={()=>setTab('write')}>创作</button><button className={tab==='outline'?'selected':''} onClick={()=>setTab('outline')}>大纲</button></div></div></nav>{tab==='outline'?<OutlinePage novel={workspace.novel} workspace={workspace} proposal={proposal} busy={busy} generate={createOutline} improve={improveOutline} apply={applyProposal} refresh={refresh} tell={tell}/>:<div className="desk"><aside className="chapters"><div className="side-title"><span>章节</span><button className="icon" onClick={add}>＋</button></div>{workspace.chapters.map(c=><div className={`chapter-row ${chapter?.id===c.id?'active':''}`} key={c.id} onClick={()=>select(c.id)}><span>第 {c.sequence} 章</span><b>{c.title}</b><small>{c.status==='confirmed'?'已确认':'草稿'} · {c.actual_words} 字</small></div>)}{!workspace.chapters.length&&<button className="add-first" onClick={add}>＋ 新建第一章</button>}</aside><section className="editor">{chapter?<ChapterEditor novel={workspace.novel} chapter={chapter} refresh={refresh} deleteChapter={deleteChapter} setIssues={setIssues} tell={tell} busy={busy} setBusy={setBusy} execute={execute}/>:<div className="empty">从左侧新建一个章节开始。</div>}</section><Inspector workspace={workspace} issues={issues} runId={runId} events={runEvents} runs={runs} reloadRuns={loadRuns} resume={resume} cancel={cancel} openOutline={()=>setTab('outline')}/></div>}</main>
}

function ChapterEditor({novel,chapter,refresh,deleteChapter,setIssues,tell,busy,setBusy,execute}:{novel:Novel;chapter:Chapter;refresh:(id?:number)=>void;deleteChapter:(c:Chapter)=>void;setIssues:(x:Issue[])=>void;tell:(x:string)=>void;busy:boolean;setBusy:(x:boolean)=>void;execute:(task:string,input:object,chapterId?:number,onEvent?:(event:AgentEvent)=>void)=>Promise<any>}){
 const[title,setTitle]=useState(chapter.title),[outline,setOutline]=useState(chapter.outline),[requirements,setRequirements]=useState(chapter.writing_requirements),[improve,setImprove]=useState(''),[preview,setPreview]=useState<any>(null)
 useEffect(()=>{setTitle(chapter.title);setOutline(chapter.outline);setRequirements(chapter.writing_requirements);setPreview(null)},[chapter.id])
 const content=()=>document.querySelector<HTMLTextAreaElement>('#content')?.value||chapter.content
 const save=async(extra:any={})=>{try{await api(`/novels/${novel.id}/chapters/${chapter.id}`,'PATCH',{title,outline,writing_requirements:requirements,content:content(),...extra});await refresh(chapter.id);tell('已保存')}catch(e:any){tell(e.message)}}
 const suggest=async()=>{try{setBusy(true);const r=await execute('suggest_outline',{},chapter.id);setTitle(r.title||title);setOutline(r.outline||'');tell('已生成可编辑建议大纲')}catch(e:any){tell(e.message)}finally{setBusy(false)}}
 const improveOutline=async()=>{if(!improve.trim())return tell('请输入改进要求');try{setBusy(true);const r=await execute('improve_chapter_outline',{improvement_request:improve},chapter.id);setPreview(r)}catch(e:any){tell(e.message)}finally{setBusy(false)}}
 const generate=async()=>{try{await save();setBusy(true);let text='';const r=await execute('generate_chapter',{},chapter.id,event=>{if(event.event_type==='content_delta'){text+=event.data.delta;const el=document.querySelector<HTMLTextAreaElement>('#content');if(el)el.value=text}});await save({content:r.content||text});tell('正文草稿已生成')}catch(e:any){tell(e.message)}finally{setBusy(false)}}
 const validate=async()=>{try{setBusy(true);const r=await execute('validate_chapter',{},chapter.id);setIssues(r.issues||[]);tell(r.passed?'校验通过':'发现需要留意的问题')}catch(e:any){tell(e.message)}finally{setBusy(false)}}
 const confirm=async()=>{try{await save();setBusy(true);const extracted=await execute('extract_memory',{},chapter.id);await api(`/novels/${novel.id}/chapters/${chapter.id}/confirm`,'POST',{extracted});await refresh(chapter.id);tell('章节已确认，记忆草稿已提取')}catch(e:any){tell(e.message)}finally{setBusy(false)}}
 return <><div className="editor-head"><input className="title-input" value={title} onChange={e=>setTitle(e.target.value)}/><div className="chapter-actions"><button className="ghost" onClick={()=>save()}>保存草稿</button><button className="ghost" disabled={busy} onClick={validate}>校验</button><button className="ghost" disabled={busy} onClick={confirm}>确认章节</button><details className="more-menu"><summary>•••</summary><button className="danger-action" onClick={()=>deleteChapter(chapter)}>删除本章</button></details></div></div><details className="outline-box" open><summary>章节大纲与写作要求 <em>{outline?'已填写':'待补充'}</em></summary><textarea value={outline} onChange={e=>setOutline(e.target.value)} placeholder="这一章要发生什么？"/><textarea value={requirements} onChange={e=>setRequirements(e.target.value)} placeholder="本章补充要求（可选）"/>{!outline&&<button className="soft" disabled={busy} onClick={suggest}>✦ AI 建议章节大纲</button>}<div className="improve-box"><input value={improve} onChange={e=>setImprove(e.target.value)} placeholder="例如：加强悬疑感，保留既有剧情"/><button className="soft" disabled={busy} onClick={improveOutline}>AI 改进本章大纲</button></div>{preview&&<div className="preview"><b>{preview.change_summary}</b><p>{preview.reasoning_summary}</p>{preview.warnings?.map((x:string,i:number)=><small key={i}>⚠ {x}</small>)}<button onClick={()=>{setTitle(preview.title||title);setOutline(preview.outline||outline);setPreview(null)}}>采用这份预览</button><button className="ghost" onClick={()=>setPreview(null)}>放弃</button></div>}</details><textarea id="content" className="prose" defaultValue={chapter.content} placeholder="在这里开始写作，或让 AI 按大纲生成正文……"/><div className="compose-bar"><span>{chapter.actual_words} 字 · {chapter.target_words||'未设目标'}</span><div><button className="ghost" onClick={()=>save()}>保存草稿</button><button disabled={busy} onClick={generate}>{busy?'正在创作…':'✦ 生成章节'}</button></div></div></>
}

function Inspector({workspace,issues,runId,events,runs,reloadRuns,resume,cancel,openOutline}:{workspace:Workspace;issues:Issue[];runId:string;events:AgentEvent[];runs:any[];reloadRuns:()=>void;resume:(id:string)=>Promise<any>;cancel:(id:string)=>Promise<void>;openOutline:()=>void}){
 return <aside className="inspector"><section><h3>创作辅助</h3><p className="muted">人物、时间线和设定会辅助本章创作。</p></section><RunPanel runId={runId} events={events} runs={runs} reload={reloadRuns} resume={resume} cancel={cancel}/><section><h4>人物状态 <button className="link-button" onClick={openOutline}>编辑人物</button></h4>{workspace.characters.length?workspace.characters.slice(0,5).map(c=><div className="memory" key={c.id}><b>{c.name}｜{c.is_main_character?'主角':'重要角色'}</b><span>{c.current_goal||c.current_status||c.profile||'尚未记录状态'}</span></div>):<p className="muted">尚未建立人物设定。<button className="link-button" onClick={openOutline}>前往大纲添加人物</button></p>}</section><section><h4>时间线</h4>{workspace.timeline.slice(-4).map(x=><div className="memory" key={x.id}><b>{x.time_description||'未标注时间'} · {x.location||'未知地点'}</b><span>{x.content}</span></div>)}</section><section><h4>校验结果</h4>{issues.length?issues.map((i,n)=><div className={`issue ${i.severity}`} key={n}><b>{i.type}</b><p>{i.description}</p><small>建议：{i.suggestion}</small></div>):<p className="muted">校验不会直接改动正文。</p>}</section><section><h4>设定与伏笔</h4>{workspace.facts.slice(-4).map(f=><div className="memory" key={f.id}><b>{f.fact_type}</b><span>{f.content}</span></div>)}</section></aside>
}
function RunPanel({runId,events,runs,reload,resume,cancel}:{runId:string;events:AgentEvent[];runs:any[];reload:()=>void;resume:(id:string)=>Promise<any>;cancel:(id:string)=>Promise<void>}){
 const current=runs.find(x=>x.id===runId)
 const context=events.find(x=>x.event_type==='context')?.data
 const isRunning=Boolean(runId)&&events.some(x=>x.event_type==='status'&&x.data.stage==='running')&&!events.some(x=>x.event_type==='done')
 const recoverable=runs.filter(r=>['interrupted','cancelled','failed','paused'].includes(r.status)).slice(0,3)
 return <section className="run-panel">
   <h4>Agent 运行 <button className="tiny" onClick={reload}>刷新</button></h4>
   {runId&&<>
     <p className="run-id">{runId.slice(0,8)} · {current?.status||'运行中'}</p>
     {context&&<div className="run-context"><b>上下文 {context.estimated_tokens}/{context.token_budget} Token</b><small>已带入：{context.included_items?.join('、')}</small>{context.compressed_items?.length>0&&<small>已压缩：{context.compressed_items.join('、')}</small>}</div>}
     <div className="run-events">{events.filter(x=>x.event_type!=='content_delta').slice(-8).map((e,i)=><p key={i}>{e.event_type==='status'||e.event_type==='tool'?e.data.message:e.event_type==='warning'?`⚠ ${e.data.message}`:e.event_type==='done'?'✓ 运行结束':e.event_type==='error'?`错误：${e.data.message}`:'已获得结果'}</p>)}</div>
     {isRunning&&<button className="tiny danger-link" onClick={()=>cancel(runId)}>停止并保留草稿</button>}
   </>}
   {recoverable.map(r=><div className="recover-run" key={r.id}><span>{r.task_type} · {r.status}</span><button className="tiny" onClick={()=>resume(r.id)}>从中断处恢复</button></div>)}
 </section>
}
function CharacterCard({c,edit,toggle,remove}:{c:Character;edit:(c:Character)=>void;toggle:(c:Character)=>void;remove:(c:Character)=>void}){return <div className="memory character-card"><b>{c.name} {c.confirmed&&<i className="confirmed">已确认</i>}</b><span>{c.current_goal||c.goal||c.profile||'尚未补充设定'}</span>{c.arc_or_growth&&<small>成长线：{c.arc_or_growth}</small>}<div><button className="tiny" onClick={()=>edit(c)}>编辑</button><button className="tiny" onClick={()=>toggle(c)}>{c.is_main_character?'取消主角':'设为主角'}</button><button className="tiny danger-link" onClick={()=>remove(c)}>删除</button></div></div>}

function OutlinePage({novel,workspace,proposal,busy,generate,improve,apply,refresh,tell}:{novel:Novel;workspace:Workspace;proposal:Proposal|null;busy:boolean;generate:()=>void;improve:(x:string)=>void;apply:(x?:number[])=>void;refresh:()=>void;tell:(x:string)=>void}){
 const [outline,setOutline]=useState(novel.master_outline||''),[feedback,setFeedback]=useState(''),[selected,setSelected]=useState<number[]>([]),[revisions,setRevisions]=useState<any[]>([])
 useEffect(()=>{setOutline(novel.master_outline||'')},[novel.id])
 const rows=proposal?.outline?.chapters??proposal?.chapters??[]
 const save=async()=>{try{await api(`/novels/${novel.id}`,'PATCH',{master_outline:outline});await refresh();tell('总纲已保存，并保留了修改前快照')}catch(e:any){tell(e.message)}}
 const loadRevisions=async()=>{try{setRevisions(await api(`/novels/${novel.id}/outline-revisions`))}catch(e:any){tell(e.message)}}
 const restore=async(id:number)=>{if(!window.confirm('恢复该版本？当前总纲会先自动保存为快照。'))return;try{await api(`/novels/${novel.id}/outline-revisions/${id}/restore`,'POST');await refresh();tell('已恢复总纲版本')}catch(e:any){tell(e.message)}}
 const toggle=(n:number)=>setSelected(s=>s.includes(n)?s.filter(x=>x!==n):[...s,n])
 const doImprove=async()=>{if(!feedback.trim())return tell('请输入改进要求');try{if(outline!==novel.master_outline){await api(`/novels/${novel.id}`,'PATCH',{master_outline:outline});await refresh()}await improve(feedback)}catch(e:any){tell(e.message)}}
 const previewOutline=proposal?.outline?.content??proposal?.master_outline
 return <section className="outline-page"><header><div><p className="eyebrow">STORY ARCHITECT</p><h1>小说大纲</h1><p className="sub">先完善故事基础设定，再让 AI 按反馈迭代；预览不会直接覆盖现有内容。</p></div><div><button className="ghost" onClick={save}>保存总纲</button><button disabled={busy} onClick={generate}>✦ AI 生成大纲</button></div></header><StorySettings workspace={workspace} refresh={refresh} tell={tell}/><textarea className="master-outline" value={outline} onChange={e=>setOutline(e.target.value)} placeholder="写下当前总纲、人物关系或已有剧情。"/><section className="feedback"><h3>基于当前大纲继续改进</h3><textarea value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="例如：前三章出现核心冲突；女主前期更克制，成长更明显；保留第一幕只调整中后期。"/><button disabled={busy} onClick={doImprove}>{busy?'分析中…':'✦ AI 改进大纲'}</button><button className="ghost" onClick={loadRevisions}>查看版本快照</button>{revisions.map(r=><div className="revision" key={r.id}><span>{new Date(r.created_at).toLocaleString()} · {r.reason}</span><button className="tiny" onClick={()=>restore(r.id)}>恢复</button></div>)}</section>{proposal&&<section className="proposal"><div className="proposal-head"><div><h2>改进建议预览</h2><p>{proposal.change_summary||'新的总纲与章节规划'}</p><small>{proposal.reasoning_summary}</small>{proposal.warnings?.map((x,i)=><small className="warning" key={i}>⚠ {x}</small>)}</div><div><button onClick={()=>apply(selected.length?selected:undefined)}>应用所选章节</button></div></div><label>改进后的总纲<textarea className="master-outline small" value={previewOutline||''} onChange={()=>tell('可在预览中查看；应用时使用当前 AI 结果。')}/></label><p className="muted">已确认章节默认不会被应用；勾选草稿章节后可选择性应用。</p>{rows.map((c:any,i:number)=>{const n=Number(c.chapter_number??c.sequence??i+1);return <article key={n} className="preview-chapter"><input type="checkbox" checked={selected.includes(n)} onChange={()=>toggle(n)}/><div><b>第 {n} 章 · {c.title}</b><small>{c.change_type||'modified'}</small><p>{c.outline}</p></div></article>})}<div className="actions"><button className="ghost" onClick={()=>apply([])}>仅应用总纲</button><button onClick={()=>apply(rows.map((c:any,i:number)=>Number(c.chapter_number??c.sequence??i+1)))}>应用所有可改章节</button></div></section>}</section>
}

function StorySettings({workspace,refresh,tell}:{workspace:Workspace;refresh:()=>void;tell:(x:string)=>void}){
 const [selected,setSelected]=useState<Character|null>(null),[adding,setAdding]=useState(false)
 return <section className="story-settings"><div><h2>故事基础设定</h2><p><b>主旨：</b>{workspace.novel.theme||'尚未填写'}　<b>题材：</b>{workspace.novel.genre||'未分类'}　<b>文风：</b>{workspace.novel.default_style||'未设定'}</p></div><div className="character-section-head"><h3>主要人物</h3><button className="soft" onClick={()=>setAdding(true)}>＋ 添加人物</button></div><div className="character-list">{workspace.characters.map(c=><button className="character-name-card" key={c.id} onClick={()=>setSelected(c)}><span>{c.name}</span>{c.is_main_character&&<small>主角</small>}</button>)}{!workspace.characters.length&&<p className="muted character-empty">尚未建立人物设定。点击“添加人物”开始。</p>}</div>{(selected||adding)&&<CharacterDialog novelId={workspace.novel.id} character={selected} close={()=>{setSelected(null);setAdding(false)}} refresh={refresh} tell={tell}/>}</section>
}

function CharacterDialog({novelId,character,close,refresh,tell}:{novelId:number;character:Character|null;close:()=>void;refresh:()=>void;tell:(x:string)=>void}){
 const blank={name:'',profile:'',appearance:'',goal:'',personality:'',relationships:'',current_status:'',confirmed:false,is_main_character:false,importance:3,current_location:'',current_goal:'',current_emotion_or_state:'',arc_or_growth:'',status:'draft'}
 const [value,setValue]=useState<any>(character?{...character}:blank),[editing,setEditing]=useState(!character),[saving,setSaving]=useState(false)
 const update=(field:string,next:any)=>setValue((old:any)=>({...old,[field]:next}))
 const save=async(e:any)=>{e.preventDefault();if(!value.name.trim())return tell('请填写人物姓名');try{setSaving(true);if(character)await api(`/novels/${novelId}/characters/${character.id}`,'PATCH',value);else await api(`/novels/${novelId}/characters`,'POST',value);await refresh();tell('人物设定已保存');close()}catch(e:any){tell(e.message)}finally{setSaving(false)}}
 const rows:[string,string][]=[['身份或角色定位',value.profile],['外貌',value.appearance],['性格与核心动机',value.personality],['当前目标',value.current_goal||value.goal],['当前位置',value.current_location],['当前情绪或状态',value.current_emotion_or_state||value.current_status],['成长弧线',value.arc_or_growth],['人物关系',value.relationships]]
 return <Modal close={close}><section className="character-dialog"><div className="character-dialog-head"><div><p className="eyebrow">CHARACTER PROFILE</p><h2>{character?character.name:'添加人物'}</h2></div>{character&&!editing&&<button onClick={()=>setEditing(true)}>编辑人物</button>}</div>{editing?<form className="form character-form" onSubmit={save}><div className="character-form-grid"><label>姓名<input required value={value.name} onChange={e=>update('name',e.target.value)}/></label><label>身份或角色定位<input value={value.profile||''} onChange={e=>update('profile',e.target.value)}/></label><label className="wide">外貌<textarea value={value.appearance||''} onChange={e=>update('appearance',e.target.value)} placeholder="例如：身形、发色、常见穿着、显著特征"/></label><label>性格与核心动机<input value={value.personality||''} onChange={e=>update('personality',e.target.value)}/></label><label>当前目标<input value={value.current_goal||''} onChange={e=>update('current_goal',e.target.value)}/></label><label>当前位置<input value={value.current_location||''} onChange={e=>update('current_location',e.target.value)}/></label><label>当前情绪或状态<input value={value.current_emotion_or_state||''} onChange={e=>update('current_emotion_or_state',e.target.value)}/></label><label>成长弧线<input value={value.arc_or_growth||''} onChange={e=>update('arc_or_growth',e.target.value)}/></label><label>人物关系<input value={value.relationships||''} onChange={e=>update('relationships',e.target.value)}/></label></div><div className="character-toggles"><label><input type="checkbox" checked={value.is_main_character} onChange={e=>update('is_main_character',e.target.checked)}/> 设为主角</label><label><input type="checkbox" checked={value.confirmed} onChange={e=>update('confirmed',e.target.checked)}/> 确认为正式设定</label></div><div className="actions"><button type="button" className="ghost" onClick={()=>character?setEditing(false):close()}>取消</button><button disabled={saving}>{saving?'保存中…':'保存人物'}</button></div></form>:<div className="character-summary">{character?.is_main_character&&<span className="character-badge">主角</span>}{character?.confirmed&&<span className="character-badge">已确认设定</span>}{rows.filter(([,text])=>text).map(([label,text])=><div key={label}><small>{label}</small><p>{text}</p></div>)}{!rows.some(([,text])=>text)&&<p className="muted">尚未补充人物详情。</p>}</div>}</section></Modal>
}
