import { ReactNode, useEffect, useMemo, useState } from 'react'
import { Chapter, Character, Fact, json, Novel, request, streamChapter, Timeline } from './api'

type Workspace={novel:Novel;chapters:Chapter[];characters:Character[];facts:Fact[];timeline:Timeline[]}
type Issue={type:string;severity:string;description:string;suggestion:string}
type Proposal={master_outline?:string;chapters?:any[];change_summary?:string;reasoning_summary?:string;affected_chapters?:number[];warnings?:string[];outline?:{content:string;chapters:any[]}}
const newNovel={title:'',genre:'',theme:'',target_words:80000,default_style:''}
const api=(path:string,method='GET',body?:unknown)=>request<any>(path,json(method,body))

function Modal({children,close}:{children:ReactNode;close:()=>void}){return <div className="veil"><section className="modal"><button className="icon close" onClick={close}>×</button>{children}</section></div>}

export default function App(){
 const [novels,setNovels]=useState<Novel[]>([]),[workspace,setWorkspace]=useState<Workspace|null>(null),[chapterId,setChapterId]=useState<number|null>(null),[notice,setNotice]=useState(''),[create,setCreate]=useState(false)
 const tell=(text:string)=>{setNotice(text);window.setTimeout(()=>setNotice(''),4500)}
 const loadShelf=()=>request<Novel[]>('/novels').then(setNovels).catch((e:Error)=>tell(e.message))
 const open=async(id:number,select?:number)=>{try{const w=await request<Workspace>(`/novels/${id}/workspace`);setWorkspace(w);setChapterId(select??w.chapters[0]?.id??null)}catch(e:any){tell(e.message)}}
 useEffect(()=>{loadShelf()},[])
 const createNovel=async(data:any)=>{try{const n=await api('/novels','POST',data);setCreate(false);await loadShelf();await open(n.id);tell('小说已创建')}catch(e:any){tell(e.message)}}
 const removeNovel=async(n:Novel)=>{if(!window.confirm(`确定永久删除《${n.title}》吗？\n\n这会删除该小说的全部大纲、章节、正文、人物、时间线、摘要、设定事实和 AI 记录，且无法恢复。`))return;try{await api(`/novels/${n.id}`,'DELETE');if(workspace?.novel.id===n.id)setWorkspace(null);await loadShelf();tell('小说已删除')}catch(e:any){tell(e.message)}}
 const chapter=useMemo(()=>workspace?.chapters.find(x=>x.id===chapterId)||workspace?.chapters[0],[workspace,chapterId])
 return <>{workspace?<Workbench workspace={workspace} chapter={chapter} select={setChapterId} refresh={(id?:number)=>open(workspace.novel.id,id??chapter?.id)} back={()=>{setWorkspace(null);loadShelf()}} removeNovel={()=>removeNovel(workspace.novel)} tell={tell}/>:<Shelf novels={novels} open={open} create={()=>setCreate(true)} remove={removeNovel}/>} {create&&<NovelForm close={()=>setCreate(false)} submit={createNovel}/>} {notice&&<div className="toast">{notice}</div>}</>
}

function Shelf({novels,open,create,remove}:{novels:Novel[];open:(id:number)=>void;create:()=>void;remove:(n:Novel)=>void}){return <main className="shelf"><header><div><p className="eyebrow">NOVELWRITER</p><h1>你的故事，从这里长出来。</h1><p className="sub">每一部小说都有独立的创作记忆与设定。</p></div><button onClick={create}>＋ 新建小说</button></header><div className="book-grid">{novels.map((n,i)=><article className={`book book-${i%4}`} key={n.id}><button className="book-open" onClick={()=>open(n.id)}><span>{n.genre||'未分类'}</span><h2>{n.title}</h2><p>{n.theme||'尚未写下故事主旨'}</p><footer>{n.target_words?.toLocaleString()||'—'} 字目标</footer></button><button className="book-delete" onClick={()=>remove(n)}>删除</button></article>)}{!novels.length&&<div className="empty"><span>✦</span><h2>书架还是空的</h2><p>创建第一本小说，开始建立属于它的世界。</p><button onClick={create}>创建小说</button></div>}</div></main>}

function NovelForm({close,submit}:{close:()=>void;submit:(data:any)=>void}){const[f,setF]=useState(newNovel);const on=(e:any)=>setF({...f,[e.target.name]:e.target.name==='target_words'?Number(e.target.value):e.target.value});return <Modal close={close}><p className="eyebrow">NEW NOVEL</p><h2>创建一本小说</h2><form className="form" onSubmit={e=>{e.preventDefault();submit(f)}}><label>书名<input required name="title" value={f.title} onChange={on}/></label><div className="two"><label>题材<input name="genre" value={f.genre} onChange={on}/></label><label>目标字数<input name="target_words" type="number" value={f.target_words} onChange={on}/></label></div><label>故事主旨<textarea name="theme" value={f.theme} onChange={on}/></label><label>默认文风<textarea name="default_style" value={f.default_style} onChange={on}/></label><div className="actions"><button type="button" className="ghost" onClick={close}>取消</button><button>创建并进入</button></div></form></Modal>}

function Workbench({workspace,chapter,select,refresh,back,removeNovel,tell}:{workspace:Workspace;chapter?:Chapter;select:(n:number)=>void;refresh:(n?:number)=>void;back:()=>void;removeNovel:()=>void;tell:(x:string)=>void}){
 const [tab,setTab]=useState<'write'|'outline'>('write'),[busy,setBusy]=useState(false),[issues,setIssues]=useState<Issue[]>([]),[proposal,setProposal]=useState<Proposal|null>(null)
 const add=async()=>{const sequence=Math.max(0,...workspace.chapters.map(x=>x.sequence))+1;try{const c=await api(`/novels/${workspace.novel.id}/chapters`,'POST',{sequence,title:`第${sequence}章`,status:'draft'});await refresh(c.id)}catch(e:any){tell(e.message)}}
 const deleteChapter=async(c:Chapter)=>{const warning=c.status==='confirmed'?'\n\n此章节已确认，删除可能使后续章节的时间线、人物状态和大纲引用失效。':'';if(!window.confirm(`删除第 ${c.sequence} 章《${c.title}》？\n\n将删除正文、摘要、AI 任务以及直接关联的提取数据。${warning}`))return;try{await api(`/novels/${workspace.novel.id}/chapters/${c.id}`,'DELETE');await refresh();tell('章节已删除并重排后续序号；建议重新校验后续章节。')}catch(e:any){tell(e.message)}}
 const improveOutline=async(requestText:string)=>{try{setBusy(true);const r=await api(`/novels/${workspace.novel.id}/ai/improve-outline`,'POST',{improvement_request:requestText});setProposal(r.result);setTab('outline')}catch(e:any){tell(e.message)}finally{setBusy(false)}}
 const createOutline=async()=>{try{setBusy(true);const r=await api(`/novels/${workspace.novel.id}/ai/outline`,'POST',{theme:workspace.novel.theme,genre:workspace.novel.genre,target_words:workspace.novel.target_words||80000,chapter_count:12,style:workspace.novel.default_style});setProposal({master_outline:r.result.master_outline,chapters:r.result.chapters});setTab('outline')}catch(e:any){tell(e.message)}finally{setBusy(false)}}
 const applyProposal=async(selected?:number[])=>{if(!proposal)return;const outline=proposal.outline?.content??proposal.master_outline;const rows=proposal.outline?.chapters??proposal.chapters??[];try{setBusy(true);await api(`/novels/${workspace.novel.id}/ai/apply-outline-improvement`,'POST',{master_outline:outline,chapters:rows,apply_chapter_numbers:selected});setProposal(null);await refresh();tell('已应用选择的草稿章节；已确认章节保持不变。')}catch(e:any){tell(e.message)}finally{setBusy(false)}}
 return <main className="workbench"><nav className="topbar"><button className="wordmark" onClick={back}>‹ 书架</button><div><strong>{workspace.novel.title}</strong><span>{workspace.novel.genre||'小说工作台'}</span></div><div className="tabs"><button className={tab==='write'?'selected':''} onClick={()=>setTab('write')}>创作</button><button className={tab==='outline'?'selected':''} onClick={()=>setTab('outline')}>大纲</button><button className="danger-link" onClick={removeNovel}>删除小说</button></div></nav>{tab==='outline'?<OutlinePage novel={workspace.novel} proposal={proposal} busy={busy} generate={createOutline} improve={improveOutline} apply={applyProposal} refresh={refresh} tell={tell}/>:<div className="desk"><aside className="chapters"><div className="side-title"><span>章节</span><button className="icon" onClick={add}>＋</button></div>{workspace.chapters.map(c=><div className={`chapter-row ${chapter?.id===c.id?'active':''}`} key={c.id} onClick={()=>select(c.id)}><span>第 {c.sequence} 章</span><b>{c.title}</b><small>{c.status==='confirmed'?'已确认':'草稿'} · {c.actual_words} 字</small><button className="mini-delete" onClick={e=>{e.stopPropagation();deleteChapter(c)}}>删除</button></div>)}{!workspace.chapters.length&&<button className="add-first" onClick={add}>＋ 新建第一章</button>}</aside><section className="editor">{chapter?<ChapterEditor novel={workspace.novel} chapter={chapter} refresh={refresh} deleteChapter={deleteChapter} setIssues={setIssues} tell={tell} busy={busy} setBusy={setBusy}/>:<div className="empty">从左侧新建一个章节开始。</div>}</section><Inspector workspace={workspace} refresh={refresh} issues={issues} tell={tell}/></div>}</main>
}

function ChapterEditor({novel,chapter,refresh,deleteChapter,setIssues,tell,busy,setBusy}:{novel:Novel;chapter:Chapter;refresh:(id?:number)=>void;deleteChapter:(c:Chapter)=>void;setIssues:(x:Issue[])=>void;tell:(x:string)=>void;busy:boolean;setBusy:(x:boolean)=>void}){
 const[title,setTitle]=useState(chapter.title),[outline,setOutline]=useState(chapter.outline),[requirements,setRequirements]=useState(chapter.writing_requirements),[improve,setImprove]=useState(''),[preview,setPreview]=useState<any>(null)
 useEffect(()=>{setTitle(chapter.title);setOutline(chapter.outline);setRequirements(chapter.writing_requirements);setPreview(null)},[chapter.id])
 const content=()=>document.querySelector<HTMLTextAreaElement>('#content')?.value||chapter.content
 const save=async(extra:any={})=>{try{await api(`/novels/${novel.id}/chapters/${chapter.id}`,'PATCH',{title,outline,writing_requirements:requirements,content:content(),...extra});await refresh(chapter.id);tell('已保存')}catch(e:any){tell(e.message)}}
 const suggest=async()=>{try{setBusy(true);const r=await api(`/novels/${novel.id}/chapters/${chapter.id}/ai/suggest-outline`,'POST');setTitle(r.result.title||title);setOutline(r.result.outline||'');tell('已生成可编辑建议大纲')}catch(e:any){tell(e.message)}finally{setBusy(false)}}
 const improveOutline=async()=>{if(!improve.trim())return tell('请输入改进要求');try{setBusy(true);const r=await api(`/novels/${novel.id}/chapters/${chapter.id}/ai/improve-outline`,'POST',{improvement_request:improve});setPreview(r.result)}catch(e:any){tell(e.message)}finally{setBusy(false)}}
 const generate=async()=>{try{await save();setBusy(true);let text='';await streamChapter(`/novels/${novel.id}/chapters/${chapter.id}/ai/generate`,{},x=>{text+=x;const el=document.querySelector<HTMLTextAreaElement>('#content');if(el)el.value=text});await save({content:text});tell('正文草稿已生成')}catch(e:any){tell(e.message)}finally{setBusy(false)}}
 const validate=async()=>{try{setBusy(true);const r=await api(`/novels/${novel.id}/chapters/${chapter.id}/ai/validate`,'POST');setIssues(r.issues||[]);tell(r.passed?'校验通过':'发现需要留意的问题')}catch(e:any){tell(e.message)}finally{setBusy(false)}}
 const confirm=async()=>{try{await save();setBusy(true);await api(`/novels/${novel.id}/chapters/${chapter.id}/confirm`,'POST');await refresh(chapter.id);tell('章节已确认，记忆草稿已提取')}catch(e:any){tell(e.message)}finally{setBusy(false)}}
 return <><div className="editor-head"><input className="title-input" value={title} onChange={e=>setTitle(e.target.value)}/><div><button className="ghost" onClick={()=>save()}>保存</button><button className="ghost" disabled={busy} onClick={validate}>校验</button><button className="ghost" disabled={busy} onClick={confirm}>确认章节</button><button className="danger-link" onClick={()=>deleteChapter(chapter)}>删除</button></div></div><details className="outline-box" open><summary>章节大纲与写作要求 <em>{outline?'已填写':'待补充'}</em></summary><textarea value={outline} onChange={e=>setOutline(e.target.value)} placeholder="这一章要发生什么？"/><textarea value={requirements} onChange={e=>setRequirements(e.target.value)} placeholder="本章补充要求（可选）"/>{!outline&&<button className="soft" disabled={busy} onClick={suggest}>✦ AI 建议章节大纲</button>}<div className="improve-box"><input value={improve} onChange={e=>setImprove(e.target.value)} placeholder="例如：加强悬疑感，保留既有剧情"/><button className="soft" disabled={busy} onClick={improveOutline}>AI 改进本章大纲</button></div>{preview&&<div className="preview"><b>{preview.change_summary}</b><p>{preview.reasoning_summary}</p>{preview.warnings?.map((x:string,i:number)=><small key={i}>⚠ {x}</small>)}<button onClick={()=>{setTitle(preview.title||title);setOutline(preview.outline||outline);setPreview(null)}}>采用这份预览</button><button className="ghost" onClick={()=>setPreview(null)}>放弃</button></div>}</details><textarea id="content" className="prose" defaultValue={chapter.content} placeholder="在这里开始写作，或让 AI 按大纲生成正文……"/><div className="compose-bar"><span>{chapter.actual_words} 字 · {chapter.target_words||'未设目标'}</span><div><button className="ghost" onClick={()=>save()}>保存草稿</button><button disabled={busy} onClick={generate}>{busy?'正在创作…':'✦ 生成章节'}</button></div></div></>
}

function Inspector({workspace,refresh,issues,tell}:{workspace:Workspace;refresh:(id?:number)=>void;issues:Issue[];tell:(x:string)=>void}){
 const addCharacter=async()=>{const name=window.prompt('主要主角姓名：');if(!name)return;try{await api(`/novels/${workspace.novel.id}/characters`,'POST',{name,is_main_character:true,confirmed:false,status:'draft'});await refresh();tell('主角已添加，请继续补充人物资料')}catch(e:any){tell(e.message)}}
 const editCharacter=async(c:Character)=>{const profile=window.prompt('人物设定（可编辑）',c.profile);if(profile===null)return;const current_goal=window.prompt('当前目标',c.current_goal||c.goal||'');if(current_goal===null)return;const arc_or_growth=window.prompt('成长弧线',c.arc_or_growth||'');if(arc_or_growth===null)return;try{await api(`/novels/${workspace.novel.id}/characters/${c.id}`,'PATCH',{profile,current_goal,arc_or_growth,confirmed:c.confirmed,status:c.confirmed?'confirmed':c.status});await refresh();tell('人物资料已更新')}catch(e:any){tell(e.message)}}
 const toggleMain=async(c:Character)=>{try{await api(`/novels/${workspace.novel.id}/characters/${c.id}`,'PATCH',{is_main_character:!c.is_main_character});await refresh()}catch(e:any){tell(e.message)}}
 const removeCharacter=async(c:Character)=>{if(!window.confirm(`删除人物「${c.name}」？`))return;try{await api(`/novels/${workspace.novel.id}/characters/${c.id}`,'DELETE');await refresh()}catch(e:any){tell(e.message)}}
 return <aside className="inspector"><section><h3>创作记忆</h3><p className="muted">已确认主角是最高优先级写作约束。</p></section><section><h4>主要主角 <button className="tiny" onClick={addCharacter}>＋ 添加</button></h4>{workspace.characters.filter(c=>c.is_main_character).map(c=><CharacterCard key={c.id} c={c} edit={editCharacter} toggle={toggleMain} remove={removeCharacter}/>)}{!workspace.characters.some(c=>c.is_main_character)&&<p className="muted">尚未设置主要主角。</p>}</section><section><h4>其他人物</h4>{workspace.characters.filter(c=>!c.is_main_character).map(c=><CharacterCard key={c.id} c={c} edit={editCharacter} toggle={toggleMain} remove={removeCharacter}/>)}</section><section><h4>时间线</h4>{workspace.timeline.slice(-4).map(x=><div className="memory" key={x.id}><b>{x.time_description||'未标注时间'} · {x.location||'未知地点'}</b><span>{x.content}</span></div>)}</section><section><h4>编审校验</h4>{issues.length?issues.map((i,n)=><div className={`issue ${i.severity}`} key={n}><b>{i.type}</b><p>{i.description}</p><small>建议：{i.suggestion}</small></div>):<p className="muted">校验不会直接改动正文。</p>}</section><section><h4>设定事实</h4>{workspace.facts.slice(-4).map(f=><div className="memory" key={f.id}><b>{f.fact_type}</b><span>{f.content}</span><i className={f.status==='confirmed'?'confirmed':''}>{f.status}</i></div>)}</section></aside>
}
function CharacterCard({c,edit,toggle,remove}:{c:Character;edit:(c:Character)=>void;toggle:(c:Character)=>void;remove:(c:Character)=>void}){return <div className="memory character-card"><b>{c.name} {c.confirmed&&<i className="confirmed">已确认</i>}</b><span>{c.current_goal||c.goal||c.profile||'尚未补充设定'}</span>{c.arc_or_growth&&<small>成长线：{c.arc_or_growth}</small>}<div><button className="tiny" onClick={()=>edit(c)}>编辑</button><button className="tiny" onClick={()=>toggle(c)}>{c.is_main_character?'取消主角':'设为主角'}</button><button className="tiny danger-link" onClick={()=>remove(c)}>删除</button></div></div>}

function OutlinePage({novel,proposal,busy,generate,improve,apply,refresh,tell}:{novel:Novel;proposal:Proposal|null;busy:boolean;generate:()=>void;improve:(x:string)=>void;apply:(x?:number[])=>void;refresh:()=>void;tell:(x:string)=>void}){
 const [outline,setOutline]=useState(novel.master_outline||''),[feedback,setFeedback]=useState(''),[selected,setSelected]=useState<number[]>([]),[revisions,setRevisions]=useState<any[]>([])
 useEffect(()=>{setOutline(novel.master_outline||'')},[novel.id])
 const rows=proposal?.outline?.chapters??proposal?.chapters??[]
 const save=async()=>{try{await api(`/novels/${novel.id}`,'PATCH',{master_outline:outline});await refresh();tell('总纲已保存，并保留了修改前快照')}catch(e:any){tell(e.message)}}
 const loadRevisions=async()=>{try{setRevisions(await api(`/novels/${novel.id}/outline-revisions`))}catch(e:any){tell(e.message)}}
 const restore=async(id:number)=>{if(!window.confirm('恢复该版本？当前总纲会先自动保存为快照。'))return;try{await api(`/novels/${novel.id}/outline-revisions/${id}/restore`,'POST');await refresh();tell('已恢复总纲版本')}catch(e:any){tell(e.message)}}
 const toggle=(n:number)=>setSelected(s=>s.includes(n)?s.filter(x=>x!==n):[...s,n])
 const doImprove=async()=>{if(!feedback.trim())return tell('请输入改进要求');try{if(outline!==novel.master_outline){await api(`/novels/${novel.id}`,'PATCH',{master_outline:outline});await refresh()}await improve(feedback)}catch(e:any){tell(e.message)}}
 const previewOutline=proposal?.outline?.content??proposal?.master_outline
 return <section className="outline-page"><header><div><p className="eyebrow">STORY ARCHITECT</p><h1>小说大纲</h1><p className="sub">先写下你的想法，再让 AI 按反馈迭代；预览不会直接覆盖现有内容。</p></div><div><button className="ghost" onClick={save}>保存总纲</button><button disabled={busy} onClick={generate}>✦ AI 生成大纲</button></div></header><textarea className="master-outline" value={outline} onChange={e=>setOutline(e.target.value)} placeholder="写下当前总纲、人物关系或已有剧情。"/><section className="feedback"><h3>基于当前大纲继续改进</h3><textarea value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="例如：前三章出现核心冲突；女主前期更克制，成长更明显；保留第一幕只调整中后期。"/><button disabled={busy} onClick={doImprove}>{busy?'分析中…':'✦ AI 改进大纲'}</button><button className="ghost" onClick={loadRevisions}>查看版本快照</button>{revisions.map(r=><div className="revision" key={r.id}><span>{new Date(r.created_at).toLocaleString()} · {r.reason}</span><button className="tiny" onClick={()=>restore(r.id)}>恢复</button></div>)}</section>{proposal&&<section className="proposal"><div className="proposal-head"><div><h2>改进建议预览</h2><p>{proposal.change_summary||'新的总纲与章节规划'}</p><small>{proposal.reasoning_summary}</small>{proposal.warnings?.map((x,i)=><small className="warning" key={i}>⚠ {x}</small>)}</div><div><button onClick={()=>apply(selected.length?selected:undefined)}>应用所选章节</button></div></div><label>改进后的总纲<textarea className="master-outline small" value={previewOutline||''} onChange={()=>tell('可在预览中查看；应用时使用当前 AI 结果。')}/></label><p className="muted">已确认章节默认不会被应用；勾选草稿章节后可选择性应用。</p>{rows.map((c:any,i:number)=>{const n=Number(c.chapter_number??c.sequence??i+1);return <article key={n} className="preview-chapter"><input type="checkbox" checked={selected.includes(n)} onChange={()=>toggle(n)}/><div><b>第 {n} 章 · {c.title}</b><small>{c.change_type||'modified'}</small><p>{c.outline}</p></div></article>})}<div className="actions"><button className="ghost" onClick={()=>apply([])}>仅应用总纲</button><button onClick={()=>apply(rows.map((c:any,i:number)=>Number(c.chapter_number??c.sequence??i+1)))}>应用所有可改章节</button></div></section>}</section>
}
